README.md

I just edited it on Github, not sure what change it found in the drupal link.

Fixing minor typo in Readme

---

db/file.js
role_permissions.js
test/lib/util.js
test/test

it seems our move to non-strict broke quite some things (tests were not working anymore)
I guess there will be more refactoring needed for the other adapters.
Overall i think it's a good move for the project, as most modules are written in es6/strict.

fixed broken (non-strict) file-adapter + tests

---

index.js

Error Handler which logs and sends to user is updated. The condition statement to check where the user has permission or not is updated.

error handler, condition statement updated

---

index.js
test/tests/collection.init.js

this will prevent expressa from breaking other express middleware (it assumed noncollections being a collection)

bugfixed nonexisting collection + environment-switch

---

README.md
index.js

easy prev/next/totalpages-properties added when `&page=1` is passed to GET /:collection

added pagination

---

db/file.js

this one was tricky to debug (authentication was *sometimes* not working)

bugfix: return after all properties are tested, instead of incomplete objects

---

auth/jwt.js
index.js

(big userobjects make big jsonwebtokens)

prevent chrome crash on requestsize

---

package-lock.json
package.json

Make use of cross-env to allow setting of environment variableof both windows and mac (and maybe others?)

Cross Platform Environment Variables

---

package-lock.json
package.json

Use rimraf for better compatibility

Cross Platform rm -rf

---

index.js
modules/permissions/permissions.js

This should have been toLowerCase, but then thought about it and that wasn't needed either.
While ive got you, not sure simply filtering our `pgpool` was the most elegant solution but couldn't quickly find another way to get only actual collections

Not toLocaleLowerCase

---

middleware/users_permissions.js

Fix for missing api error code

missing error code for this api error

---

controllers/collections.js
index.js
util.js

export createPagination as a util so that can easilly create pagination for custom endpoints

export createPagination as a util

---

auth/index.js
auth/jwt.js
controllers/install.js
controllers/users.js
index.js
listeners_collection_permissions.js
listeners_users.js
middleware/users_permissions.js
modules/core/core.js
modules/permissions/permissions.js
test/users.js
util.js

@thomas4019 This is still a work in progress and i am still testing, but wanted you to be able to start having a look and make sure you dont hate it. 
I battled to find an elegant solution that worked by applying the same set of logic to all 'authenticated' collections, and also worked correctly during server install. 
I was thinking by opening up the auth routes to any collection is might cause a vulnerability which i have attempted to address - if you could please look out for anything else id appreciate it.
I have done some limited testing and so far so good

Collections With Authentication Flow

---

modules/admin/src/router/index.js
modules/admin/src/views/ListDocuments2.vue

- Added search filters for each column. (Only for string and number).
- Add rows per page options to pagination.
- Change the Home component import path so that it runs on case-sensitive systems.

Feature: Add search filters to columns

---

modules/admin/src/views/ListDocuments2.vue

Feature: implement download all

---

modules/admin/src/views/ListDocuments2.vue

Implemented filter for custom columns

Implemented filter for custom columns

---

controllers/install.js
modules/permissions/permissions.js

Fixes https://github.com/thomas4019/expressa/issues/161
Prevent automatic overwriting of Admin permissions that may have been assigned manually

Preserve Admin Permissions

---

auth/index.js
auth/jwt.js
controllers/users.js
index.js
middleware/permissions.js
middleware/users_permissions.js

The fact that `doLogin` was expecting the `req` as a parameter was causing some headaches in my project.
So i set out to refactor it a bit to accept explicit parameters.
I also found that signing with the email address is not necessary anymore? Though i will need your input on this point please.
Since `doLogin` is exposed as a util this is a breaking change - though not sure major version increase necessary
Refactored `userPermissions` to `permissions` to make more generic

Login Refactor

---

modules/admin/src/components/JSONEditor.vue

Add some css to ensure consistent and constrained image previews in the JSON editor

Json Editor Image Previews

---

modules/admin/src/views/ListDocuments2.vue

Implement selectable columns

---

index.js

Just expose all the utils, exposing one by one a bit honerous, didnt see any risk

Expose All Utils

---

modules/admin/package.json
modules/admin/src/router/index.js
modules/admin/src/views/Endpoints.vue
modules/admin/src/views/ListDocuments2.vue

Added a new page that lets us see data coming from an endpoint in tabular format. We can also apply filters.

Add endpoint page

---

controllers/collections.js

Provide a way to add custom data onto the response, without modifying the document being queried

Custom Response Data

---

auth/index.js
db/file.js
db/memory.js
index.js
listeners_users.js
util.js

Expose more and refactor a bit

More Utils

---

db/postgres.js
listeners_validation.js
util.js

Various utils to help consumers create postgres queries from mongo queries

Mongo to Postgres Utils

---

package-lock.json
package.json
util.js

Useful to validate single properties within a schema

Validate Schema Property

---

package.json
util.js

Account for Arrays in getSchemaProperty

Account for Arrays in getSchemaProperty

---

middleware/permissions.js
util.js

Role Permission Util
